### ISSUE TITLE
simfinR::simfinR_get_price_data() failing

### ISSUE THREAD

**Issue by AmanuelMedhanie** [msperlin/simfinR#3]
First off. Thank you for creating this package! It's wonderful. Starting today I experienced the following issue:

simfinR::simfinR_get_price_data() is failing to fetch data for valid simfin Ids 

Reproducible example:
SimFinIds <- c(101897)

simfinR::simfinR_get_price_data(id_companies = SimFinIds, api_key = readLines(here::here("assets","key.txt")))

-------Response: Error in simfinR_id_to_name(id_sim, api_key) : Cant find name for 101897
Despite this error, I'm able to retrieve data from the simfin web api for this simfin ID using postman (see below)

Details:
- I have a simfin+ account
- Using simfinR version 0.2.2
- Using Microsoft R Open 3.5.3

![image](https://user-images.githubusercontent.com/39957113/85145107-afb0a900-b211-11ea-8bdf-7abd29d69764.png)

**Comment by msperlin** [comment]
Thanks, I'll have a look as soon as I can. 

In the meanwhile, try cleanig (deleting) the cache files and re-execute the script. Let me know if that works.

**Comment by AmanuelMedhanie** [comment]
At the time I did try deleting the cache files and re-executing the script but the problem persisted. I tried it again this morning and the entire script ran without issue as it had been doing for several days so I have no clue why this function wasn't working. I'll close this out. Thanks for your time.

**Comment by msperlin** [comment]
Its an issue with the API, I've seem this behavior before. I'll check it nonetheless.
