### ISSUE TITLE
Join forces? 

### ISSUE THREAD

**Issue by matthiasgomolka** [msperlin/simfinR#8]
Since there seems to be more active development in the recent past, I was wondering if it would make sense to join forces and put all the effort going into simfinR and simfinapi (https://github.com/matthiasgomolka/simfinapi) into a single project.

What do you think?

**Comment by msperlin** [comment]
Hi Mathias. I'm always up for collaboration. What do you suggest?

**Comment by msperlin** [comment]
I also agree that to consolidate is smarter (why would be both bang our heads on the same problem).

**Comment by matthiasgomolka** [comment]
> Hi Mathias. I'm always up for collaboration. What do you suggest? 

Hi Marcelo, sounds good. I'll try to dig a little deeper into your code to make concrete suggestions.

From a first impression I think it makes more sense to build upon simfinapi because there exists already a larger infrastructure such as tests on all major several platforms via Github Actions. Therefore it should be easier to merge features from simfinR into simfinapi. 

Additionally, simfinapi is already referenced on https://simfin.com/data/api and builds upon the API version 2.

Feel free to disagree 😁

**Comment by msperlin** [comment]
You got good points Matthias. Even though I have some felling over simfinR, your code is more up to date. 
@superchordate how do you fell about us joining forces for simfinapi?

**Comment by superchordate** [comment]
I really like the idea. I stumbled across simfinR first and then started using simfinapi also since my impression is simfin v1 and v2 both have things the other doesn't. So the best approach might be to combine the two to get full coverage under a single package. I'm comfortable continuing with a focus on simfinapi. I need to take another look to be sure but I think we can bring some simfinR stuff into simfinapi for a quick win.

**Comment by superchordate** [comment]
Thanks for suggesting @matthiasgomolka!

**Comment by matthiasgomolka** [comment]
Great to hear! 

> my impression is simfin v1 and v2 both have things the other doesn't. 

I think, it would be helpful to clearly identify the things that are missing in simfinapi. Since you've tried both packages: Would you be able to start off a list?

**Comment by msperlin** [comment]
Nice guys. I'll archive simfinR, link to simfinapi and remove from CRAN. I'll need some time to look at the new code, but I'll do that as soon as possible.

**Comment by superchordate** [comment]
@matthiasgomolka the one thing that seems to be missing is the info about share classes. I'm not sure if this information is valuable.

* simfinR_get_share_classes calls https://simfin.com/api/v1/companies/id/%s/shares/classes/list
* simfinR_get_shares_outstanding calls https://simfin.com/api/v1/companies/id/%s/shares/classes/%s/outstanding
* simfinR_get_price_by_class calls https://simfin.com/api/v1/companies/id/%s/shares/classes/%s/prices

I've shared sample datasets for TWLO at https://drive.google.com/drive/folders/1KXKvVCN-u8jDwVeFsrvlA7LE5E4DtqVQ?usp=sharing

I wonder if it'd be worth bringing these into simfinapi and sending calls to v1.
